import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes } from 'react-router-dom';
import './style.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:3000';
function Page({title,children}:{title:string,children:React.ReactNode}){return <main className="page"><h1>{title}</h1>{children}</main>}
function Nav(){return <nav><b>VibeShelf</b><Link to="/">Mood Home</Link><Link to="/recommendations">Recommendations</Link><Link to="/library">Bookshelf</Link><Link to="/add-book">Add Book</Link><Link to="/search">Search</Link><Link to="/reviews">Community Reviews</Link><Link to="/profile">Profile</Link></nav>}
function Home(){const [moods,setMoods]=React.useState<any[]>([]); React.useEffect(()=>{fetch(API+'/api/moods').then(r=>r.json()).then(setMoods).catch(()=>setMoods([]))},[]); return <Page title="Mood Randomizer Home Dashboard"><p>Choose your current mood to get a fast book recommendation.</p><div className="grid">{moods.map(m=><Link className="card" to={`/recommendations?mood=${m.mood_id}`} key={m.mood_id}><h2>{m.name}</h2><p>{m.description}</p></Link>)}</div></Page>}
function Recommendations(){const [books,setBooks]=React.useState<any[]>([]); React.useEffect(()=>{const mood=new URLSearchParams(location.search).get('mood'); const url=mood?`${API}/api/moods/${mood}/recommendations`:`${API}/api/books`; fetch(url).then(r=>r.json()).then(setBooks).catch(()=>setBooks([]))},[]); return <Page title="Mood-Matched Recommendations"><div className="grid">{books.map(b=><article className="card" key={b.book_id}><h2>{b.title}</h2><p>{b.author}</p><button>Skip / Not Interested</button><button>Save to Bookshelf</button></article>)}</div></Page>}
function Library(){return <Page title="Digital Bookshelf"><p>Track reading status: want to read, currently reading, finished, paused, dropped, or re-reading.</p><BookList /></Page>}
function Search(){return <Page title="Search and Filter Books"><p>Search by title, author, or genre.</p><BookList /></Page>}
function BookList(){const [books,setBooks]=React.useState<any[]>([]); React.useEffect(()=>{fetch(API+'/api/books').then(r=>r.json()).then(setBooks).catch(()=>setBooks([]))},[]); return <div className="grid">{books.map(b=><article className="card" key={b.book_id}><h2>{b.title}</h2><p>{b.author} • {b.genre}</p><p>Avg rating: {b.average_rating ?? 0}</p></article>)}</div>}
function AddBook(){const [msg,setMsg]=React.useState(''); async function submit(e:any){e.preventDefault(); const fd=new FormData(e.currentTarget); const body=Object.fromEntries(fd.entries()); if(!body.title||!body.author){setMsg('Title and author are required.'); return;} const r=await fetch(API+'/api/books',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); setMsg(r.ok?'Book added.':'Could not add book. Check the form.')} return <Page title="Add Book / Book Details"><form onSubmit={submit} className="form"><input name="title" placeholder="Title" required/><input name="author" placeholder="Author" required/><input name="genre" placeholder="Genre"/><input name="isbn" placeholder="ISBN"/><textarea name="description" placeholder="Description"/><button>Add Book</button><p>{msg}</p></form></Page>}
function Reviews(){return <Page title="Community Reviews / Public Profile"><p>Reviews connect to a public username and bio.</p><form className="form"><input placeholder="Book ID"/><select><option>5 stars</option><option>4 stars</option></select><textarea placeholder="Write review text"/><button type="button">Submit Review</button></form></Page>}
function Profile(){return <Page title="Account and Profile"><p>Username, bio, and publicly reviewed books display here.</p><div className="card"><h2>MayaReads</h2><p>Fantasy reader who likes emotional stories.</p></div></Page>}
function App(){return <BrowserRouter><Nav/><Routes><Route path="/" element={<Home/>}/><Route path="/recommendations" element={<Recommendations/>}/><Route path="/library" element={<Library/>}/><Route path="/add-book" element={<AddBook/>}/><Route path="/search" element={<Search/>}/><Route path="/reviews" element={<Reviews/>}/><Route path="/profile" element={<Profile/>}/></Routes></BrowserRouter>}
ReactDOM.createRoot(document.getElementById('root')!).render(<App/>);
