import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import dotenv from 'dotenv';
import bookRoutes from './routes/books.js';
import moodRoutes from './routes/moods.js';
import reviewRoutes from './routes/reviews.js';

dotenv.config();
const app = express();
const PORT = process.env.PORT || 3000;
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' }));
app.use(morgan('dev'));
app.use(express.json());
app.get('/health', (req, res) => res.json({ status: 'OK', timestamp: new Date().toISOString() }));
app.use('/api/books', bookRoutes);
app.use('/api/moods', moodRoutes);
app.use('/api/reviews', reviewRoutes);
app.use((req, res) => res.status(404).json({ error: 'Route not found' }));
app.use((err, req, res, next) => res.status(500).json({ error: 'Internal server error', details: err.message }));
app.listen(PORT, () => console.log(`VibeShelf API running at http://localhost:${PORT}`));
